{{- $fullName := include "linstor.fullname" . -}}
{{- if .Values.configurator.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-configurator
data:
  functions.sh: |
    {{- .Files.Get "scripts/functions.sh" | nindent 4 }}
  configurator.sh: |
    #!/bin/bash
    set -e
    . $(dirname $0)/functions.sh
    echo "Node hostname: $HOSTNAME"

    load_params
    wait_satellite
    wait_controller
    {{- with .Values.configurator.autoJoinNodes }}
    register_node
    {{- end }}

    {{- range .Values.configurator.nodeConfigurations }}
    if [[ $HOSTNAME =~ {{ .regex }} ]]; then
      echo 'Handling configuration for "{{ .regex }}"'
      {{- range .interfaces }}
      configure_interface {{ .name | quote }} {{ .ip | quote }}
      {{- end }}
      {{- range .storagePools }}
      configure_storage_pool {{ .name | quote }} {{ .providerKind | quote }} {{ mustToJson .props | quote }}
      {{- end }}
    fi
    {{- end }}

    finish
{{- end }}
